# Generated by Codex on 2026-03-28

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edms_api', '0002_workrecord_closed_date_workrecord_closing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorDocumentReview',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('latest_revision', models.IntegerField(default=1)),
                ('previous_revision', models.IntegerField(blank=True, null=True)),
                ('document_family_key', models.CharField(db_index=True, max_length=255)),
                ('design_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('BYPASSED', 'Bypassed')], default='PENDING', max_length=20)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('bypass_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('latest_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_document_reviews', to='edms_api.document')),
                ('pl_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reviews', to='edms_api.plitem')),
                ('previous_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_document_reviews', to='edms_api.document')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_document_reviews', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', 'created_at'], name='suprev_status_idx'),
                    models.Index(fields=['pl_item', 'status'], name='suprev_pl_status_idx'),
                    models.Index(fields=['latest_document', 'status'], name='suprev_doc_status_idx'),
                ],
            },
        ),
    ]
