# Generated by Django 5.2.12 on 2026-04-03 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edms_api", "0009_document_document_family_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "created_at"], name="edms_api_au_user_id_5a2959_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["module", "created_at"], name="edms_api_au_module_102a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "created_at"], name="edms_api_au_severit_fab85d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["source_system", "created_at"],
                name="edms_api_do_source__486ba1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="edms_api_do_status_37b343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["linked_pl", "created_at"],
                name="edms_api_do_linked__f32122_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["status", "date"], name="edms_api_wo_status_ebfc9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["status", "created_at"], name="edms_api_wo_status_3c0e50_idx"
            ),
        ),
    ]
