// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/RefinedGlow.tsx": () =>
    import("../components/mockups/login-variants/RefinedGlow.tsx"),
  "./components/mockups/login-variants/Structured.tsx": () =>
    import("../components/mockups/login-variants/Structured.tsx"),
};
